### DISCUSSION TITLE
Unresolved classification errors

### DISCUSSION THREAD

**Discussion by Nixinova** [Nixinova/LinguistJS#11] [General]
github-linguist uses its samples folder to help classification when ambiguous files are found, however linguist-js doesn't do this as it would take way too many web requests, so I'm not sure how to fix all these classification errors.

If anyone has any ideas to help classification in these cases please put them here.

List is from analysing github-linguist's [samples folder](https://github.com/github/linguist/tree/master/samples) and will be updated whenever.

<details><summary>Analysis results as of v3.0.0 count=140</summary>

```yaml
Adblock Filter List/abp-filters-anti-cv.txt: Text
Adblock Filter List/anti-facebook.txt: Text
Adblock Filter List/fake-news.txt: Text
Adblock Filter List/Imperial Units Remover.txt: Text
Adblock Filter List/test_rules.txt: Text
AMPL/CT2.mod: Linux Kernel Module
AngelScript/botmanager.as: ActionScript
AngelScript/payload.as: ActionScript
Befunge/aturley.bf: Beef
Befunge/beer7.bf: Beef
Befunge/befunge3.bf: Beef
Befunge/cascade.bf: Beef
Befunge/mycorand.bf: Beef
BitBake/tclibc-newlib.inc: Assembly
BitBake/xorg-driver-common.inc: Assembly
C++/ClasspathVMSystemProperties.inc: Assembly
C++/initClasses.inc: Assembly
C++/instances.inc: Assembly
CoffeeScript/build.cake: C#
Component Pascal/Example.cp: C++
Cue Sheet/sample1.cue: CUE
Cue Sheet/sample2.cue: CUE
DenizenScript/sample1.dsc: Debian Package Control File
DenizenScript/sample2.dsc: Debian Package Control File
Emacs Lisp/.emacs.desktop: Common Lisp
Emacs Lisp/filenames/.spacemacs: Common Lisp
Fstar/FStar.DependentMap.fsti: F*
Genie/Class.gs: GLSL
Genie/Hello.gs: GLSL
HLSL/corridor.fx: FLUX
HLSL/jellyfish.fx: FLUX
HLSL/noise.fx: FLUX
HTML/rpanel.inc: Assembly
HTML/tailDel.inc: Assembly
INI/filenames/hosts: Hosts File
INI/ms.cfg: HAProxy
Java Properties/libraries.properties: INI
JavaScript/chart_composers.gs: GLSL
JavaScript/intro.js.frag: GLSL
JavaScript/itau.gs: GLSL
JavaScript/merge.js: AppleScript
JavaScript/outro.js.frag: GLSL
jq/builtin.jq: JSONiq
jq/sample.jq: JSONiq
KiCad Legacy Layout/tc14badge.brd: Eagle
KiCad Schematic/buttons.sch: Eagle
KiCad Schematic/buzzer.sch: Eagle
KiCad Schematic/ciaaConector.sch: Eagle
KiCad Schematic/gedda-junk.sch: Eagle
KiCad Schematic/ultimate-temp-controller.sch: Eagle
KiCad Schematic/Volume.sch: Eagle
Kickstart/fedora-32-live-jam-xfce-pipewire.ks: KerboScript
Kickstart/mysql.ks: KerboScript
Kickstart/sample_end.ks: KerboScript
KoLmafia ASH/newDG.ash: AGS Script
KoLmafia ASH/tt_kingliberated.ash: AGS Script
Limbo/cat.b: Brainfuck
Limbo/lock.b: Brainfuck
Logos/string1.x: DirectX 3D File
M/arrays.m: Limbo
M/fibonacci.m: Limbo
M/forloop.m: Limbo
M/helloworld.m: Limbo
M/ifelse.m: Limbo
M/indirectfunctions.m: Limbo
M/mileage.m: Limbo
M/nesting.m: Limbo
MATLAB/Check_plot.m: Limbo
MATLAB/matlab_class.m: Limbo
MATLAB/normalize.m: Limbo
Moocode/hello.moo: Mercury
Moocode/moocode_toolkit.moo: Mercury
Moocode/toy.moo: Mercury
Motoko/erc20.mo: Modelica
Motoko/queue.mo: Modelica
MQL5/Regex.mqh: MQL4
Nasal/damage.nas: Assembly
Nasal/kx165tso.nas: Assembly
Nginx/example.com.vhost: ApacheConf
Objective-C/cocoa_monitor.m: Wolfram Language
Objective-J/AppController.j: Jasmin
Objective-J/iTunesLayout.j: Jasmin
Objective-J/LightsOff.j: Jasmin
Parrot Internal Representation/hello.pir: Parrot Assembly
Pawn/Check.inc: Assembly
Pawn/fixed.inc: Assembly
Pawn/fixes.inc: Assembly
Pawn/mfile.inc: Assembly
Pawn/y_testing.inc: Assembly
PHP/prefix.fcgi: Lua
Protocol Buffer Text Format/ProjectSettings.pbt: PowerBuilder
Protocol Buffer Text Format/Tree.pbt: PowerBuilder
Puppet/hiera_include.pp: Pascal
Puppet/stages-example.pp: Pascal
Raku/hash.t: Perl
Raku/man-or-boy.t: Perl
Roff/he.mdoc: Roff Manpage
RouterOS Script/BackupAndUpdate.rsc: Rascal
RouterOS Script/config.rsc: Rascal
RouterOS Script/console-dump.rsc: Rascal
RouterOS Script/vlans.rsc: Rascal
RPM Spec/apache.spec: Python
RPM Spec/erlang-erlydtl.spec: Python
RPM Spec/manos.spec: Python
Ruby/any.spec: Python
Scala/99-bottles-of-beer: Shell
Scala/scala: Shell
Scheme/lambdastar.sls: SaltStack
Scheme/sboyer.sch: Eagle
ShaderLab/DepthOfField.shader: GLSL
ShaderLab/Fog.shader: GLSL
ShaderLab/Uber.shader: GLSL
SQL/AvailableInSearchSel.prc: PLSQL
SQL/hostcache_set_state.inc: Assembly
SQL/videodb.ddl: PLSQL
Survex data/data.svx: mdsvex
Terra/arith.t: Perl
Terra/arrayt.t: Perl
Terra/benchmark_nbody.t: Perl
Type Language/builtin.tl: Teal
Type Language/scheme.tl: Teal
Unix Assembly/support.S: Assembly
VBA/dictionary.cls: Visual Basic 6.0
VBA/WorkbookReporter.cls: Visual Basic 6.0
VBA/WorksheetView.cls: Visual Basic 6.0
Visual Basic 6.0/Adjustments_BlackAndWhite.frm: VBA
Visual Basic 6.0/frmProcMan.frm: VBA
WebIDL/AnimationEvent.webidl: BASIC
WebIDL/Fetch.webidl: BASIC
Wolfram Language/MiscCalculations.nb: Text
Wolfram Language/MiscCalculations2.nb: Text
XML/battlescribe.gst: Gosu
XML/Case.workflow: HCL
XML/HITSP_C32.sch: Eagle
XML/holobloc-sample.res: ReScript
XML/namespace-strict.sch: Eagle
XML/oasis-table.sch: Eagle
XML/some-ideas.mm: Objective-C++
XML/XmlIO.pluginspec: Ruby
Zmodel/todo.zmodel: Zmodel
```
(&minus;1 since v2.6)

</details>

Compare: [v2.6 VS v3.0](https://www.diffchecker.com/42IWdoNF/)
